// This file is auto-generated by Lovable. Do not edit directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjibabicdpnupqszsqhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqaWJhYmljZHBudXBxc3pzcWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1OTg0MTAsImV4cCI6MjA4NTE3NDQxMH0.I8tcJZHNw0036sinAH2lJhCn5RXSrN2KU25LQpfnivw";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  },
});

export default supabase;
